#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: ActiveModifierItemHUD

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ActiveModifierItemHUD.ActiveModifierItemHUD_C
// 0x0008 (0x0218 - 0x0210)
class UActiveModifierItemHUD_C final : public UCommonUserWidget
{
public:
	class UImage*                                 ImageModifier;                                     // 0x0210(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void AssignIcon(const struct FSlateBrush& inIconSlateBrush);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ActiveModifierItemHUD_C">();
	}
	static class UActiveModifierItemHUD_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UActiveModifierItemHUD_C>();
	}
};

}

