#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BacchusEquippedItemReloadWidget

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "FortniteUI_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BacchusEquippedItemReloadWidget.BacchusEquippedItemReloadWidget_C
// 0x0060 (0x03D0 - 0x0370)
class UBacchusEquippedItemReloadWidget_C final : public UAthenaEquippedItemBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0370(0x0008)(Transient, DuplicateTransient)
	class UImage*                                 AmmoIcon;                                          // 0x0378(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       MagazineAmmoCount;                                 // 0x0380(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             OutOfAmmo;                                         // 0x0388(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       ResourceCount;                                     // 0x0390(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Split1;                                            // 0x0398(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       StandAloneAmmoCount;                               // 0x03A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       SurplusAmmoCount;                                  // 0x03A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonWidgetSwitcher*                  SwitcherContent;                                   // 0x03B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 UtilityItemImage;                                  // 0x03B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FLinearColor                           OutOfAmmoColor;                                    // 0x03C0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BacchusEquippedItemReloadWidget(int32 EntryPoint);
	void Construct();
	void UtilityItemTypeChanged(class AFortWeapon* Weapon, class UFortWeaponItemDefinition* Item);
	void UtilityItemCountChanged(int32 Remaining);
	void AmmoChanged(int32 MagazineAmmoCount_0, int32 BackupAmmoCount, int32 TotalRemaining);
	void HasAmmoChanged(bool bHasAmmo);
	void WeaponTypeChanged(EEquippedWeaponDisplay Mode);
	void ResourceTypeChanged(class UFortResourceItemDefinition* Item, int32 ResourceCount_0);
	void AmmoTypeChanged(class AFortWeaponRanged* RangedWeapon, class UFortWorldItemDefinition* Item);
	void ResourceCountChanged(int32 ResourceCount_0);
	void UpdateWidgetColor(bool HasAmmo);
	struct FEventReply OnTouchStarted(const struct FGeometry& MyGeometry, const struct FPointerEvent& InTouchEvent);

	void GetCurrentAmmoText(int32 CurrentAmmoCount, class FText* CurrentAmmoText) const;
	void GetRemainingAmmoText(int32 RemainingAmmoCount, class FText* CurrentAmmoText) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BacchusEquippedItemReloadWidget_C">();
	}
	static class UBacchusEquippedItemReloadWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBacchusEquippedItemReloadWidget_C>();
	}
};

}

