#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: Border_MatchStatus_ActivePlayers

#include "Basic.hpp"

#include "Border_ItemInfoHeader_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Border_MatchStatus_ActivePlayers.Border_MatchStatus_ActivePlayers_C
// 0x0000 (0x00B0 - 0x00B0)
class UBorder_MatchStatus_ActivePlayers_C final : public UBorder_ItemInfoHeader_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Border_MatchStatus_ActivePlayers_C">();
	}
	static class UBorder_MatchStatus_ActivePlayers_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBorder_MatchStatus_ActivePlayers_C>();
	}
};

}

