#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: Border_TopBar_TimerFlash

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Border-TopBar-TimerFlash.Border-TopBar-TimerFlash_C
// 0x0000 (0x00B0 - 0x00B0)
class UBorder_TopBar_TimerFlash_C final : public UCommonBorderStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Border-TopBar-TimerFlash_C">();
	}
	static class UBorder_TopBar_TimerFlash_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBorder_TopBar_TimerFlash_C>();
	}
};

}

