#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: Border_ShellTopBar_Glow

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Border-ShellTopBar-Glow.Border-ShellTopBar-Glow_C
// 0x0000 (0x00B0 - 0x00B0)
class UBorder_ShellTopBar_Glow_C final : public UCommonBorderStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Border-ShellTopBar-Glow_C">();
	}
	static class UBorder_ShellTopBar_Glow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBorder_ShellTopBar_Glow_C>();
	}
};

}

