#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: ButtonStyle_QuestMapNode

#include "Basic.hpp"

#include "ButtonStyle_MediumBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ButtonStyle-QuestMapNode.ButtonStyle-QuestMapNode_C
// 0x0000 (0x04F0 - 0x04F0)
class UButtonStyle_QuestMapNode_C final : public UButtonStyle_MediumBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ButtonStyle-QuestMapNode_C">();
	}
	static class UButtonStyle_QuestMapNode_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonStyle_QuestMapNode_C>();
	}
};

}

