#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: Button_EmoteMenu

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "CommonBacchusButton_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass Button_EmoteMenu.Button_EmoteMenu_C
// 0x0028 (0x03F8 - 0x03D0)
class UButton_EmoteMenu_C final : public UCommonBacchusButton_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_Button_EmoteMenu_C;                 // 0x03D0(0x0008)(Transient, DuplicateTransient)
	struct FGameplayTagContainer                  Dancer;                                            // 0x03D8(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void ExecuteUbergraph_Button_EmoteMenu(int32 EntryPoint);
	void OnClicked();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Button_EmoteMenu_C">();
	}
	static class UButton_EmoteMenu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButton_EmoteMenu_C>();
	}
};

}

