#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: CollectionBookSectionTileWidget

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"
#include "FortniteGame_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass CollectionBookSectionTileWidget.CollectionBookSectionTileWidget_C
// 0x0030 (0x0938 - 0x0908)
class UCollectionBookSectionTileWidget_C final : public UFortCollectionBookSectionTileWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0908(0x0008)(Transient, DuplicateTransient)
	class UCommonBorder*                          SlotBorder;                                        // 0x0910(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UClass*                                 NormalTextStyle;                                   // 0x0918(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 CompletedTextStyle;                                // 0x0920(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 NormalBorderStyle;                                 // 0x0928(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 CompletedBorderStyle;                              // 0x0930(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_CollectionBookSectionTileWidget(int32 EntryPoint);
	void OnSectionSlotUpdate(int32 NumFilledSlots, int32 NumSlots, EFortCollectionBookState SectionState);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CollectionBookSectionTileWidget_C">();
	}
	static class UCollectionBookSectionTileWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCollectionBookSectionTileWidget_C>();
	}
};

}

