#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: CurrentReportStackingEntry

#include "Basic.hpp"

#include "CurrentReportStackingEntry_classes.hpp"
#include "CurrentReportStackingEntry_parameters.hpp"


namespace SDK
{

// Function CurrentReportStackingEntry.CurrentReportStackingEntry_C.ExecuteUbergraph_CurrentReportStackingEntry
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCurrentReportStackingEntry_C::ExecuteUbergraph_CurrentReportStackingEntry(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CurrentReportStackingEntry_C", "ExecuteUbergraph_CurrentReportStackingEntry");

	Params::CurrentReportStackingEntry_C_ExecuteUbergraph_CurrentReportStackingEntry Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CurrentReportStackingEntry.CurrentReportStackingEntry_C.InitStackingEntryFields
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EPlayerReportingStep                    DisplayedReportingStep                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class FText&                      DisplayText                                            (BlueprintVisible, BlueprintReadOnly, Parm)

void UCurrentReportStackingEntry_C::InitStackingEntryFields(EPlayerReportingStep DisplayedReportingStep, const class FText& DisplayText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CurrentReportStackingEntry_C", "InitStackingEntryFields");

	Params::CurrentReportStackingEntry_C_InitStackingEntryFields Parms{};

	Parms.DisplayedReportingStep = DisplayedReportingStep;
	Parms.DisplayText = std::move(DisplayText);

	UObject::ProcessEvent(Func, &Parms);
}


// Function CurrentReportStackingEntry.CurrentReportStackingEntry_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UCurrentReportStackingEntry_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CurrentReportStackingEntry_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CurrentReportStackingEntry.CurrentReportStackingEntry_C.SetDisplayTextFields
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UCurrentReportStackingEntry_C::SetDisplayTextFields()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CurrentReportStackingEntry_C", "SetDisplayTextFields");

	UObject::ProcessEvent(Func, nullptr);
}

}

