#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: FortReplayCameraSelectionMenu

#include "Basic.hpp"

#include "UMG_classes.hpp"
#include "Engine_structs.hpp"
#include "FortniteGame_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass FortReplayCameraSelectionMenu.FortReplayCameraSelectionMenu_C
// 0x0010 (0x0218 - 0x0208)
class UFortReplayCameraSelectionMenu_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0208(0x0008)(Transient, DuplicateTransient)
	class UVerticalBox*                           CameraList;                                        // 0x0210(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_FortReplayCameraSelectionMenu(int32 EntryPoint);
	void Construct();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"FortReplayCameraSelectionMenu_C">();
	}
	static class UFortReplayCameraSelectionMenu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortReplayCameraSelectionMenu_C>();
	}
};

}

