#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GAB_SmasherWallMelee

#include "Basic.hpp"

#include "GAB_SmasherMelee_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GAB_SmasherWallMelee.GAB_SmasherWallMelee_C
// 0x0000 (0x0990 - 0x0990)
class UGAB_SmasherWallMelee_C final : public UGAB_SmasherMelee_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GAB_SmasherWallMelee_C">();
	}
	static class UGAB_SmasherWallMelee_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGAB_SmasherWallMelee_C>();
	}
};

}

