#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GAB_GenericApplyPush

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GAB_GenericApplyPush.GAB_GenericApplyPush_C
// 0x0028 (0x0920 - 0x08F8)
class UGAB_GenericApplyPush_C final : public UFortGameplayAbility
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x08F8(0x0008)(Transient, DuplicateTransient)
	class UAnimMontage*                           PushedMontage;                                     // 0x0900(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           PushAsideTag;                                      // 0x0908(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	float                                         Time;                                              // 0x0910(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_914[0x4];                                      // 0x0914(0x0004)(Fixing Size After Last Property [ Dumper-8 ])
	class UGA_Constructor_BullRush_C*             GA_BullRush;                                       // 0x0918(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_GAB_GenericApplyPush(int32 EntryPoint);
	void EventReceived_7764EAC14FD514E952F78BA2A0CF9ABE(const struct FGameplayEventData& Payload);
	void K2_ActivateAbilityFromEvent(const struct FGameplayEventData& EventData);
	void OnBlendOut_569FFD0446FBE214B15C2B8019481F5F();
	void OnBlendOut_8D429E634F6B70CB0A894484CBF629F1();
	void OnCancelled_569FFD0446FBE214B15C2B8019481F5F();
	void OnCancelled_8D429E634F6B70CB0A894484CBF629F1();
	void OnCompleted_569FFD0446FBE214B15C2B8019481F5F();
	void OnCompleted_8D429E634F6B70CB0A894484CBF629F1();
	void OnInterrupted_569FFD0446FBE214B15C2B8019481F5F();
	void OnInterrupted_8D429E634F6B70CB0A894484CBF629F1();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GAB_GenericApplyPush_C">();
	}
	static class UGAB_GenericApplyPush_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGAB_GenericApplyPush_C>();
	}
};

}

