#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: MissionVoteNotification

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MissionVoteNotification.MissionVoteNotification_C
// 0x0008 (0x00B0 - 0x00A8)
class UMissionVoteNotification_C final : public UFortMissionVoteUINotification
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00A8(0x0008)(Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_MissionVoteNotification(int32 EntryPoint);
	void TakeAction();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MissionVoteNotification_C">();
	}
	static class UMissionVoteNotification_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMissionVoteNotification_C>();
	}
};

}

