#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: MissionPanelContent

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CommonUI_classes.hpp"
#include "RewardListEntryType_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass MissionPanelContent.MissionPanelContent_C
// 0x0028 (0x0238 - 0x0210)
class UMissionPanelContent_C final : public UCommonUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0210(0x0008)(Transient, DuplicateTransient)
	class UFortMultiSizeImage*                    MissionIcon;                                       // 0x0218(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       MissionName;                                       // 0x0220(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           MissionRewards;                                    // 0x0228(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           OverviewObjectives;                                // 0x0230(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_MissionPanelContent(int32 EntryPoint);
	void Construct();
	void UpdateMissionDisplay();
	void UpdateMissionRewards();
	void UpdateOverviewObjectives();
	void Setup_Mission_Rewards(TArray<class UFortItem*>& Array, ERewardListEntryType RewardType);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MissionPanelContent_C">();
	}
	static class UMissionPanelContent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMissionPanelContent_C>();
	}
};

}

