#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: MultiFactorAuthWidget

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass MultiFactorAuthWidget.MultiFactorAuthWidget_C
// 0x0010 (0x0360 - 0x0350)
class UMultiFactorAuthWidget_C final : public UFortMultiFactorAuthWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0350(0x0008)(Transient, DuplicateTransient)
	class UCommonTextBlock*                       CommonTextPromptText;                              // 0x0358(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void Construct();
	void ExecuteUbergraph_MultiFactorAuthWidget(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MultiFactorAuthWidget_C">();
	}
	static class UMultiFactorAuthWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMultiFactorAuthWidget_C>();
	}
};

}

