#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: PrimaryHeroActiveAbilitiesListDetailWidget

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass PrimaryHeroActiveAbilitiesListDetailWidget.PrimaryHeroActiveAbilitiesListDetailWidget_C
// 0x0018 (0x0298 - 0x0280)
class UPrimaryHeroActiveAbilitiesListDetailWidget_C final : public UFortSquadSlotItemDetailElementWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0280(0x0008)(Transient, DuplicateTransient)
	class UPerksList_C*                           PerksList;                                         // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	bool                                          EnableMouseTooltips;                               // 0x0290(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)
	bool                                          DisplayOutsideOfHeroSquad;                         // 0x0291(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_PrimaryHeroActiveAbilitiesListDetailWidget(int32 EntryPoint);
	void Construct();
	void HandlePostDifferentItemToDetailSet();
	void HandlePostDifferentSquadSlotSetBP();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PrimaryHeroActiveAbilitiesListDetailWidget_C">();
	}
	static class UPrimaryHeroActiveAbilitiesListDetailWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimaryHeroActiveAbilitiesListDetailWidget_C>();
	}
};

}

