#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: ProfileStatsAllStatsSubScreen

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "CommonUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ProfileStatsAllStatsSubScreen.ProfileStatsAllStatsSubScreen_C
// 0x0040 (0x0338 - 0x02F8)
class UProfileStatsAllStatsSubScreen_C final : public UCommonActivatablePanel
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02F8(0x0008)(Transient, DuplicateTransient)
	class UWrapBox*                               StatWrapBox;                                       // 0x0300(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FDataTableRowHandle                    BackAction;                                        // 0x0308(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FGameplayTagContainer                  StatsToDisplay;                                    // 0x0318(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void ExecuteUbergraph_ProfileStatsAllStatsSubScreen(int32 EntryPoint);
	void Construct();
	void HandleBack(bool* Passthrough);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ProfileStatsAllStatsSubScreen_C">();
	}
	static class UProfileStatsAllStatsSubScreen_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UProfileStatsAllStatsSubScreen_C>();
	}
};

}

