#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: QuestVerticalRewardInfo

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass QuestVerticalRewardInfo.QuestVerticalRewardInfo_C
// 0x0000 (0x0298 - 0x0298)
class UQuestVerticalRewardInfo_C final : public UFortRewardInfoWidget
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"QuestVerticalRewardInfo_C">();
	}
	static class UQuestVerticalRewardInfo_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UQuestVerticalRewardInfo_C>();
	}
};

}

