#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: RPG_Skeleton_AnimBlueprint

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "AnimGraphRuntime_structs.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass RPG_Skeleton_AnimBlueprint.RPG_Skeleton_AnimBlueprint_C
// 0x00F0 (0x0448 - 0x0358)
class URPG_Skeleton_AnimBlueprint_C final : public UAnimInstance
{
public:
	uint8                                         Pad_358[0x8];                                      // 0x0358(0x0008)(Fixing Size After Last Property [ Dumper-8 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0360(0x0008)(Transient, DuplicateTransient)
	struct FAnimNode_Root                         AnimGraphNode_Root_F7E820434538DD4C6AD2A1B5BCE33A39; // 0x0368(0x0040)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_782D94BD4EFDE1439B44CB93C212AD03; // 0x03A8(0x0068)()
	struct FAnimNode_RefPose                      AnimGraphNode_LocalRefPose_829520A14F89D74E64C7AEBBB88029DD; // 0x0410(0x0038)()

public:
	void ExecuteUbergraph_RPG_Skeleton_AnimBlueprint(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"RPG_Skeleton_AnimBlueprint_C">();
	}
	static class URPG_Skeleton_AnimBlueprint_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<URPG_Skeleton_AnimBlueprint_C>();
	}
};

}

