#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: s_pool_floor

#include "Basic.hpp"

#include "_WaterMeshBlueprintMaster_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass s_pool_floor.s_pool_floor_C
// 0x0000 (0x03F0 - 0x03F0)
class As_pool_floor_C final : public A_WaterMeshBlueprintMaster_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"s_pool_floor_C">();
	}
	static class As_pool_floor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<As_pool_floor_C>();
	}
};

}

