#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: ThirdPartyTab

#include "Basic.hpp"


namespace SDK::Params
{

// Function ThirdPartyTab.ThirdPartyTab_C.Activate Scroll Box
// 0x0008 (0x0008 - 0x0000)
struct ThirdPartyTab_C_Activate_Scroll_Box final
{
public:
	class UFortUINavigationManager*               CallFunc_GetUINavigationManager_ReturnValue;       // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

