#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: VehicleInfoIndicator

#include "Basic.hpp"

#include "VehicleInfoIndicator_classes.hpp"
#include "VehicleInfoIndicator_parameters.hpp"


namespace SDK
{

// Function VehicleInfoIndicator.VehicleInfoIndicator_C.ExecuteUbergraph_VehicleInfoIndicator
// ()
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UVehicleInfoIndicator_C::ExecuteUbergraph_VehicleInfoIndicator(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VehicleInfoIndicator_C", "ExecuteUbergraph_VehicleInfoIndicator");

	Params::VehicleInfoIndicator_C_ExecuteUbergraph_VehicleInfoIndicator Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function VehicleInfoIndicator.VehicleInfoIndicator_C.OnVehicleChanged
// (Event, Public, BlueprintEvent)

void UVehicleInfoIndicator_C::OnVehicleChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VehicleInfoIndicator_C", "OnVehicleChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VehicleInfoIndicator.VehicleInfoIndicator_C.OnVehicleHealthChanged
// (Event, Public, BlueprintEvent)

void UVehicleInfoIndicator_C::OnVehicleHealthChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VehicleInfoIndicator_C", "OnVehicleHealthChanged");

	UObject::ProcessEvent(Func, nullptr);
}

}

