#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: WM_Lights

#include "Basic.hpp"


namespace SDK::Params
{

// Function WM_Lights.WM_Lights_C.ExecuteUbergraph_WM_Lights
// 0x0008 (0x0008 - 0x0000)
struct WM_Lights_C_ExecuteUbergraph_WM_Lights final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_TurnOn;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};

// Function WM_Lights.WM_Lights_C.WM-Lightcontrol
// 0x0001 (0x0001 - 0x0000)
struct WM_Lights_C_WM_Lightcontrol final
{
public:
	bool                                          TurnOn;                                            // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};

}

